In [1]:
import sys, os
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import numpy as np
import pandas as pd
import scanpy as sc

We load the single-cell data using scanpy. The single-cell data is stored in a special data structure called AnnData (short: adata).

In [3]:
data = sc.read('sciplex_prepped.h5ad')

In [ ]:
data.obs.dtypes

,cell_type,dose,dose_character,dose_pattern,g1s_score,g2m_score,pathway,pathway_level_1,pathway_level_2,product_dose,...,vehicle,batch,n_counts,n_genes,mt_frac,perturbation,control,split,cov_name,cov_pert_name
index,,,,,,,,,,,,,,,,,,,,,
A05_F10_RT_BC_46_Lig_BC_56-1-0-1,MCF7,0.100,1000,2,2.952470,3.442190,JAK/STAT,JAK/STAT signaling,JAK kinase activity,WP1066_1000,...,0,1,3762.0,2122,0.103668,WP1066,0,test,MCF7_rep2,MCF7_rep2_WP1066
H06_F10_RT_BC_354_Lig_BC_124-1-0-3,MCF7,1.000,10000,1,2.730909,3.048589,JAK/STAT,JAK/STAT signaling,RTK activity,"Cerdulatinib (PRT062070, PRT2070)_10000",...,0,3,1763.0,1077,0.196256,Cerdulatinib,0,train,MCF7_rep2,MCF7_rep2_Cerdulatinib
A10_E09_RT_BC_65_Lig_BC_376-0-0-0,A549,0.100,1000,2,0.823174,2.159443,Apoptosis,Apoptotic regulation,Mitochondria-mediated apoptosis,Obatoclax Mesylate (GX15-070)_1000,...,0,0,1053.0,756,0.132953,Obatoclax,0,train,A549_rep1,A549_rep1_Obatoclax
F06_F10_RT_BC_186_Lig_BC_137-1-0-2,MCF7,0.010,100,3,2.429623,2.197367,Epigenetics,Epigenetic regulation,Histone methylation,Tazemetostat (EPZ-6438)_100,...,0,2,5374.0,2598,0.185895,Tazemetostat,0,test,MCF7_rep2,MCF7_rep2_Tazemetostat
A06_F10_RT_BC_73_Lig_BC_81-1-3,K562,0.010,100,3,0.894844,3.423042,JAK/STAT,JAK/STAT signaling,JAK kinase activity,Ruxolitinib (INCB018424)_100,...,0,3,3024.0,1768,0.047619,Ruxolitinib,0,train,K562_rep1,K562_rep1_Ruxolitinib
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B02_E09_RT_BC_55_Lig_BC_375-1-3,K562,1.000,10000,1,1.706056,2.348048,Cell Cycle,Cell cycle regulation,Aurora kinase activity,Barasertib (AZD1152-HQPA)_10000,...,0,3,2427.0,1514,0.152040,Barasertib,0,train,K562_rep2,K562_rep2_Barasertib
A01_E09_RT_BC_190_Lig_BC_369-1-0-1,MCF7,0.010,100,3,3.365521,2.396224,Apoptosis,Protein folding & Protein degradation,E3 ubiquitin ligase activity,Lenalidomide (CC-5013)_100,...,0,1,1267.0,889,0.168114,Lenalidomide,0,test,MCF7_rep1,MCF7_rep1_Lenalidomide
C12_E09_RT_BC_31_Lig_BC_273-0-0-0,A549,0.001,10,4,1.570435,2.207568,Protein Tyrosine Kinase,Tyrosine kinase signaling,RTK activity,Vandetanib (ZD6474)_10,...,0,0,2826.0,1724,0.146497,Vandetanib,0,train,A549_rep2,A549_rep2_Vandetanib
H09_F10_RT_BC_315_Lig_BC_119-1-0-3,MCF7,0.001,10,4,1.360285,0.000000,DNA Damage,Antioxidant,Antioxidant,Daphnetin_10,...,0,3,1746.0,1117,0.168958,Daphnetin,0,train,MCF7_rep2,MCF7_rep2_Daphnetin
F12_F10_RT_BC_344_Lig_BC_220-1-0-3,MCF7,1.000,10000,1,2.309293,2.503580,Epigenetics,JAK/STAT signaling,JAK kinase activity,"Baricitinib (LY3009104, INCB028050)_10000",...,0,3,5858.0,2789,0.171048,Baricitinib,0,train,MCF7_rep2,MCF7_rep2_Baricitinib

In [2]:
adatas = []
for i in range(5):
    adatas.append(sc.read(f'sciplex_raw_chunk_{i}.h5ad'))
adata = adatas[0].concatenate(adatas[1:])
adata

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'sciplex_raw_chunk_0.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

The counts are stored in adata.X

In [3]:
adata.X

<581777x58347 sparse matrix of type '<class 'numpy.float32'>'
	with 761621411 stored elements in Compressed Sparse Row format>

adata.obs is a dataframe containing annotation for each cell, such as e.g. batch, cell type, perturbation. Or other technical annotations at the cell level.

In [4]:
adata.obs

,cell_type,dose,dose_character,dose_pattern,g1s_score,g2m_score,pathway,pathway_level_1,pathway_level_2,product_dose,product_name,proliferation_index,replicate,size_factor,target,vehicle,batch
index,,,,,,,,,,,,,,,,,
A01_E09_RT_BC_100_Lig_BC_245-0-0-0,A549,1000.0,1000,2,1.155964,2.475312,TGF-beta/Smad,PKC signaling,PKC activitiy,Enzastaurin (LY317615)_1000,Enzastaurin (LY317615),2.643512,rep2,2.296651,PKC,0,0
A01_E09_RT_BC_100_Lig_BC_306-0-0-0,A549,10.0,10,4,0.000000,1.980748,DNA Damage,DNA damage & DNA repair,Nucleotide analog,Raltitrexed_10,Raltitrexed,1.980748,rep2,0.480141,DNA/RNA Synthesis,0,0
A01_E09_RT_BC_101_Lig_BC_109-0-0-0,A549,0.0,0,3,0.000000,0.000000,Vehicle,Vehicle,Vehicle,Vehicle_0,Vehicle,0.000000,rep1,0.516561,Vehicle,1,0
A01_E09_RT_BC_101_Lig_BC_229-0-0-0,A549,10.0,10,4,1.817254,2.801225,Apoptosis,Protein folding & Protein degradation,E3 ubiquitin ligase activity,Lenalidomide (CC-5013)_10,Lenalidomide (CC-5013),3.073606,rep2,0.387978,TNF-alpha,0,0
A01_E09_RT_BC_101_Lig_BC_280-0-0-0,A549,1000.0,1000,2,1.637016,0.867074,Ubiquitin,Epigenetic regulation,Histone deacetylation,Divalproex Sodium_1000,Divalproex Sodium,1.874835,rep2,0.724671,HDAC,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H12_F10_RT_BC_99_Lig_BC_172-1-4,K562,1000.0,1000,2,0.000000,1.410709,Angiogenesis,Tyrosine kinase signaling,RTK activity,PD173074_1000,PD173074,1.410709,rep1,0.645399,"FGFR,VEGFR",0,4
H12_F10_RT_BC_99_Lig_BC_226-1-4,K562,100.0,100,3,1.361383,1.361383,Epigenetics,JAK/STAT signaling,JAK kinase activity,"Baricitinib (LY3009104, INCB028050)_100","Baricitinib (LY3009104, INCB028050)",1.917388,rep1,0.689279,JAK,0,4
H12_F10_RT_BC_99_Lig_BC_337-1-4,K562,10.0,10,4,1.956512,2.080587,Epigenetics,Epigenetic regulation,Histone deacetylation,Entinostat (MS-275)_10,Entinostat (MS-275),2.645024,rep2,2.140055,HDAC,0,4
H12_F10_RT_BC_9_Lig_BC_21-1-4,K562,10000.0,10000,1,0.929037,1.402202,Epigenetics,Epigenetic regulation,Histone deacetylation,Resveratrol_10000,Resveratrol,1.722089,rep1,0.652712,"Autophagy,Sirtuin",0,4
H12_F10_RT_BC_9_Lig_BC_274-1-4,K562,10.0,10,4,1.601367,1.783351,Endocrinology & Hormones,Nuclear receptor signaling,Nuclear receptor activity,Andarine_10,Andarine,2.293501,rep1,1.010150,Androgen Receptor,0,4

adata.var is a dataframe containing annotation for each gene, usually some statistics such as dispersion, or gene names, pathways etc.

In [5]:
adata.var

,id,num_cells_expressed-0-0,num_cells_expressed-1-0,num_cells_expressed-1
index,,,,
TSPAN6,ENSG00000000003.14,4017,13320,199
TNMD,ENSG00000000005.5,3,14,3
DPM1,ENSG00000000419.12,8442,72353,11231
SCYL3,ENSG00000000457.13,4386,24120,3380
C1orf112,ENSG00000000460.16,5998,24454,9555
...,...,...,...,...
AL591163.1,ENSG00000284744.1,8,26,27
AL589702.1,ENSG00000284745.1,2,3,0
AC068587.10,ENSG00000284746.1,0,0,0
AL034417.4,ENSG00000284747.1,230,675,634
AL513220.1,ENSG00000284748.1,6,81,16

## Quality control
Check the quality of the data and remove some cells.

In [6]:
adata.obs['n_counts'] = np.ravel(adata.X.sum(1)) #number of counts in the cell
adata.obs['n_genes'] = np.ravel(np.sum(adata.X > 0, axis=1)) #number of genes with at least 1 count per cell
adata.var['mito'] = adata.var_names.str.contains("MT-") #flag for mitochondrial genes
adata.obs['mt_frac'] = np.ravel(adata.X[:, adata.var.mito].sum(1)) / adata.obs['n_counts'].values #fraction of mitochondrial gene exp, high values mean dead or bad quality cells

In [7]:
# filtering
adata = adata[adata.obs['n_counts'] > 500]
adata = adata[adata.obs['n_genes'] > 750]
adata = adata[adata.obs['mt_frac'] < 0.2]
adata

View of AnnData object with n_obs × n_vars = 244556 × 58347
    obs: 'cell_type', 'dose', 'dose_character', 'dose_pattern', 'g1s_score', 'g2m_score', 'pathway', 'pathway_level_1', 'pathway_level_2', 'product_dose', 'product_name', 'proliferation_index', 'replicate', 'size_factor', 'target', 'vehicle', 'batch', 'n_counts', 'n_genes', 'mt_frac'
    var: 'id', 'num_cells_expressed-0-0', 'num_cells_expressed-1-0', 'num_cells_expressed-1', 'mito'

## Normalization

In [8]:
adata.X.max() #check it's an int, to make sure it's count data and not preprocessed data

8555.0

In [9]:
sc.pp.subsample(adata, fraction=0.5, random_state=0)

sc.pp.normalize_per_cell(adata)
sc.pp.log1p(adata)

## Feature (gene) selection
We select only the top N most variable genes.

In [10]:
sc.pp.highly_variable_genes(adata, n_top_genes=2000, subset=True)

## Out-of-distribution selection

In [11]:
drugs = adata.obs.product_name.unique()
drugs = drugs[~np.isin(drugs, ['Vehicle'])]

In [12]:
results = []
for cond1 in drugs:
    ad1 = adata[adata.obs.product_name == cond1]
    ad2 = adata[adata.obs.product_name != cond1]
    mean1 = ad1.X.mean(0)
    mean2 = ad2.X.mean(0)
    l2 = np.linalg.norm(mean1-mean2)
    results.append({
        'cond1': cond1,
        'L2': l2
    })
df_vs_rest = pd.DataFrame(results)

Pick biggest signals

In [13]:
drug_OOD = df_vs_rest.sort_values(by='L2').tail(20).cond1.values
drug_OOD

array(['Bosutinib (SKI-606)', 'Belinostat (PXD101)', 'Dasatinib',
       '(+)-JQ1', 'Flavopiridol HCl', 'Patupilone (EPO906, Epothilone B)',
       'Tanespimycin (17-AAG)', 'Trametinib (GSK1120212)',
       'Alvespimycin (17-DMAG) HCl', 'Pracinostat (SB939)',
       'Givinostat (ITF2357)', 'Raltitrexed', 'Hesperadin', 'AR-42',
       'Abexinostat (PCI-24781)', 'CUDC-907', 'Dacinostat (LAQ824)',
       'Panobinostat (LBH589)', 'YM155 (Sepantronium Bromide)',
       'Quisinostat (JNJ-26481585) 2HCl'], dtype=object)

## Prepare for the model

In [14]:
adata.uns['fields'] = {}

In [15]:
adata.obs['perturbation'] = [x.split(' ')[0] for x in adata.obs['product_name']]
adata.uns['fields']['perturbation'] = 'perturbation'

In [16]:
adata.obs['control'] = [1 if x == 'Vehicle' else 0 for x in adata.obs['perturbation'].values]
adata.uns['fields']['control'] = 'control'

In [17]:
adata.obs['dose'] = adata.obs['dose'].astype(float) / np.max(adata.obs['dose'].astype(float))
adata.uns['fields']['dose'] = 'dose'

In [18]:
adata.uns['fields']['covariates'] = ['cell_type', 'replicate']

In [19]:
del adata.uns['log1p']

In [20]:
# split dataset

from sklearn.model_selection import train_test_split

adata.obs['split'] = 'NA'
adata.uns['fields']['split'] = 'split'

adata.obs.loc[
    (adata.obs['cell_type'] == 'MCF7') & (adata.obs['product_name'].isin(drug_OOD)),
    'split'
] = 'ood'

idx = np.where(adata.obs['split']=='NA')[0]
idx_train, idx_test = train_test_split(idx, test_size=0.2, random_state=42)

adata.obs.iloc[idx_train, adata.obs.columns.get_loc('split')] = 'train'
adata.obs.iloc[idx_test, adata.obs.columns.get_loc('split')] = 'test'

Rank DE genes (optional)

In [21]:
# this will be done in main script if it's not done here

cov_names = []
for cov in adata.uns['fields']['covariates']:
    cov_names.append(np.array(adata.obs[cov].values))
cov_names = ["_".join(c) for c in zip(*cov_names)]
adata.obs["cov_name"] = cov_names

cov_pert_names = []
for i in range(len(adata)):
    comb_name = (
        f"{adata.obs['cov_name'].values[i]}"
        f"_{adata.obs[adata.uns['fields']['perturbation']].values[i]}"
    )
    cov_pert_names.append(comb_name)
adata.obs["cov_pert_name"] = cov_pert_names

import warnings

from vci.dataset.gene_dataset import rank_genes_groups

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    rank_genes_groups(adata,
        groupby="cov_pert_name",
        reference="cov_name",
        control_key="control"
    )

In [22]:
adata.obs

,cell_type,dose,dose_character,dose_pattern,g1s_score,g2m_score,pathway,pathway_level_1,pathway_level_2,product_dose,...,vehicle,batch,n_counts,n_genes,mt_frac,perturbation,control,split,cov_name,cov_pert_name
index,,,,,,,,,,,,,,,,,,,,,
A05_F10_RT_BC_46_Lig_BC_56-1-0-1,MCF7,0.100,1000,2,2.952470,3.442190,JAK/STAT,JAK/STAT signaling,JAK kinase activity,WP1066_1000,...,0,1,3762.0,2122,0.103668,WP1066,0,test,MCF7_rep2,MCF7_rep2_WP1066
H06_F10_RT_BC_354_Lig_BC_124-1-0-3,MCF7,1.000,10000,1,2.730909,3.048589,JAK/STAT,JAK/STAT signaling,RTK activity,"Cerdulatinib (PRT062070, PRT2070)_10000",...,0,3,1763.0,1077,0.196256,Cerdulatinib,0,train,MCF7_rep2,MCF7_rep2_Cerdulatinib
A10_E09_RT_BC_65_Lig_BC_376-0-0-0,A549,0.100,1000,2,0.823174,2.159443,Apoptosis,Apoptotic regulation,Mitochondria-mediated apoptosis,Obatoclax Mesylate (GX15-070)_1000,...,0,0,1053.0,756,0.132953,Obatoclax,0,train,A549_rep1,A549_rep1_Obatoclax
F06_F10_RT_BC_186_Lig_BC_137-1-0-2,MCF7,0.010,100,3,2.429623,2.197367,Epigenetics,Epigenetic regulation,Histone methylation,Tazemetostat (EPZ-6438)_100,...,0,2,5374.0,2598,0.185895,Tazemetostat,0,test,MCF7_rep2,MCF7_rep2_Tazemetostat
A06_F10_RT_BC_73_Lig_BC_81-1-3,K562,0.010,100,3,0.894844,3.423042,JAK/STAT,JAK/STAT signaling,JAK kinase activity,Ruxolitinib (INCB018424)_100,...,0,3,3024.0,1768,0.047619,Ruxolitinib,0,train,K562_rep1,K562_rep1_Ruxolitinib
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B02_E09_RT_BC_55_Lig_BC_375-1-3,K562,1.000,10000,1,1.706056,2.348048,Cell Cycle,Cell cycle regulation,Aurora kinase activity,Barasertib (AZD1152-HQPA)_10000,...,0,3,2427.0,1514,0.152040,Barasertib,0,train,K562_rep2,K562_rep2_Barasertib
A01_E09_RT_BC_190_Lig_BC_369-1-0-1,MCF7,0.010,100,3,3.365521,2.396224,Apoptosis,Protein folding & Protein degradation,E3 ubiquitin ligase activity,Lenalidomide (CC-5013)_100,...,0,1,1267.0,889,0.168114,Lenalidomide,0,test,MCF7_rep1,MCF7_rep1_Lenalidomide
C12_E09_RT_BC_31_Lig_BC_273-0-0-0,A549,0.001,10,4,1.570435,2.207568,Protein Tyrosine Kinase,Tyrosine kinase signaling,RTK activity,Vandetanib (ZD6474)_10,...,0,0,2826.0,1724,0.146497,Vandetanib,0,train,A549_rep2,A549_rep2_Vandetanib
H09_F10_RT_BC_315_Lig_BC_119-1-0-3,MCF7,0.001,10,4,1.360285,0.000000,DNA Damage,Antioxidant,Antioxidant,Daphnetin_10,...,0,3,1746.0,1117,0.168958,Daphnetin,0,train,MCF7_rep2,MCF7_rep2_Daphnetin
F12_F10_RT_BC_344_Lig_BC_220-1-0-3,MCF7,1.000,10000,1,2.309293,2.503580,Epigenetics,JAK/STAT signaling,JAK kinase activity,"Baricitinib (LY3009104, INCB028050)_10000",...,0,3,5858.0,2789,0.171048,Baricitinib,0,train,MCF7_rep2,MCF7_rep2_Baricitinib

In [23]:
adata.write('sciplex_prepped.h5ad')